//https://leetcode-cn.com/problems/find-the-difference/
package FindtheDifference;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindtheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }

    public static char findTheDifference(String s, String t) {
        int tmp=0;
        for(int i=0; i<s.length(); i++){
            tmp =  tmp^s.charAt(i)^t.charAt(i);
        }
        return (char)(tmp^t.charAt(s.length()));

    }
}
